name: Model Building

on:
#   schedule:
#     - cron: "35 14 * * *"   # ✅ Runs every day at 19:05 IST after data_fetcher
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  contents: write  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Creating and updating model file
        run: |
          python -m src.forecaster
      #     python -m metadata_dumper
    
      
      - name: Commit updated model and metadata
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Ensure full history
          git fetch --prune --unshallow || echo "Already full clone"

          git checkout main
          git pull origin main

          # Stage files if they exist
          git add models/gold_lstm_model.h5
          #   [ -f models/model_metadata.json ] && git add models/model_metadata.json

          git commit -m "Save model and metadata automatically" || echo "No changes to commit"
          git push origin main
